export const API_SERVER='http://45.77.45.112'
export const TWITTER_CLIENT_CREDENTIAL='https://api.twitter.com/oauth2/token'
export const TWITTER_SEARCH_TWEETS='https://api.twitter.com/1.1/statuses/user_timeline.json'
export const TWITTER_CUSTOMER_KEY='qgdk0Mj3sJqFTAlCucHBqt94K'
export const TWITTER_CUSTOMER_SECRET='omPeWPCxhEKhWhVkHbVWxUJ9aUuUO8D0YfKYKjJBpOCqCiRPwf'
export const TWITTER_BEARER_TOKEN='cWdkazBNajNzSnFGVEFsQ3VjSEJxdDk0SzpvbVBlV1BDeGhFS2hXaFZrSGJWV3hVSjlhVXVVTzhEMFlmS1lLakpCcE9DcUNpUlB3Zg=='
export const RECIPIENTS_MAIL_REPORT='kevinhermawanx@gmail.com'